# Base configs
#baseurl: "https://photos.mobeigi.com"
baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""
exclude: ["images/raws"]

# UI configs
title: "xiaowuley"
subtitle: "Photography & Colouring"
author: "xiaowuley"
email: "xiaowuleyi@gmail.com"
header:
 title: "xiaowuleyi"
 subtitle: "xiaowuleyi"
footer:
 name: "Hi, I'm xiaowuleyi"
 bio: "I am a photographer and colourist."
 github: "https://github.com/xiaowuleyi"

social_urls:
  facebook: null
  twitter: "https://x.com/xiaowuleyi"
  instagram: null
  dribbble: null
  linkedin: null
  github: null

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
